# NOTE: update this with your service name
service: queryboost-typescript-lambda-starter

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  # To add your Live API Key add to your .env file and to here
  environment:
    MOCK_API_KEY: ${env:MOCK_API_KEY}

functions:
  #name for your lambda function
  starter:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/index.eventHandler
    events:
      - schedule: cron(0 12 * * ? *)
